#!/usr/bin/bash
#
# Script will create examples 3 from the documentation.
# run after example 2
#
set -e -u -o pipefail

echo "-----------"
echo " Example 3"

echo "Modifying vpn-test.servers.wg-B gateway -> client:"
    ./wg-tool --edit vpn-test.servers.wg-B

    FILE='Edits/vpn-test.servers.wg-B.mods'
    ./do-edits ex3-server $FILE
    ./wg-tool --merge $FILE

echo "Example 3 done"

exit 0


