#!/usr/bin/bash
#
# Script creates example 1 from the documentation.
#

set -e -u -o pipefail

echo "----------"
echo " Example 1"

echo "creating working directory"
    ./wg-tool -wkd ./

echo "creating vpn-test:"
    ./wg-tool -new vpn-test

    FILE='./Edits/vpn-test-info.mods'
    ./do-edits 'ex1-dns' $FILE
    ./wg-tool --merge $FILE

echo "creating vpn-test.servers.wg-A"
    ./wg-tool --new vpn-test.servers.wg-A
    ./wg-tool --edit vpn-test.servers.wg-A

    FILE='Edits/vpn-test.servers.wg-A.mods'
    ./do-edits ex1-server $FILE 
    ./wg-tool --merge $FILE

echo "creating 3 user accounts"
    ./wg-tool -new vpn-test.user-1.laptop vpn-test.user-2.laptop vpn-test.user-3.laptop

echo "networks: wg-A offers LAN"
    ./wg-tool --nets-offered-add "192.168.1.0/24" vpn-test.servers.wg-A

echo "permission networks to user profiles"
    ./wg-tool --nets-wanted-add "192.168.1.0/24" vpn-test.user-1.laptop vpn-test.user-2.laptop
    ./wg-tool --nets-wanted-add "192.168.1.32/28" vpn-test.user-3.laptop

echo "split routing for user 3"
    ./wg-tool --edit vpn-test.user-3.laptop

    FILE='Edits/vpn-test.user-3.laptop.mods'
    ./do-edits ex1-internet_wanted $FILE

    ./wg-tool --merge $FILE

echo "Example 1 done"

exit 0
