#!/usr/bin/python
#
# Does pre-determined edits on YAML configs
#
import os
import sys
from typing import Any
import yaml


def read_file(file: str) -> dict[str, Any]:
    """ read stdin """
    data: str = ''
    try:
        with open(file, 'r') as fob:
            data = fob.read()
    except OSError as exc:
        print(f'Error reading {file}: {exc}')
        return

    data_dict: dict[str, Any] = {}
    try:
        data_dict = yaml.safe_load(data)
    except yaml.YAMLError as exc:
        print(f'Error reading yaml data from stdin')
        pass
    return data_dict


def write_file(d: dict[str, Any], file: str):
    """ write to stdout """

    data: str = ''
    try:
        data = yaml.dump(d, default_flow_style=False)
    except yaml.YAMLError:
        print(f'Error dumping yaml data')
        return

    try:
        with open(file, 'w') as fob:
            fob.write(data)

    except OSError as exc:
        print(f'Error writing {file}: {exc}')

#
# Example 1
#

def ex1_dns(d1: dict[str, Any]) -> dict[str, Any]:
    d1['dns'] = ['10.10.10.10']
    return d1


def ex1_server(d1: dict[str, Any]) -> dict[str, Any]:
    d1['Endpoint'] = 'vpn_A.example.com:51820'
    d1['internet_offered'] = True
    d1['internet_wanted'] = False
    d1['post_up'] = ['/usr/bin/nft -f /etc/wireguard/scripts/postup.nft',]
    d1['post_down'] = ['/usr/bin/nft flush ruleset',]
    d1['internet_offered'] = True
    return d1


def ex1_internet_wanted(d1: dict[str, Any]) -> dict[str, Any]:
    d1['internet_wanted'] = False
    return d1


#
# Example 2
#


def ex2_server(d1: dict[str, Any]) -> dict[str, Any]:
    d1['Endpoint'] = 'vpn_B.example.com:51820'
    d1['internet_offered'] = True
    d1['internet_wanted'] = False
    d1['post_up'] = ['/usr/bin/nft -f /etc/wireguard/scripts/postup.nft', ]
    d1['post_down'] = ['/usr/bin/nft flush ruleset', ]
    d1['internet_offered'] = True
    return d1

#
# Example 3
#

def ex3_server(d1: dict[str, Any]) -> dict[str, Any]:
    d1['Endpoint'] = ''
    d1['internet_offered'] = True
    return d1

#
# Example 4
#
def ex4_vpn_net(d1: dict[str, Any]) -> dict[str, Any]:
    d1['networks'] = ['10.77.76.0/22', 'fc00:77:77::/56']
    return d1


def main():
    """
    Make edits on stdin to yaml - write to stdout
    edits are keyed by name 
    Args:
        <key> <file>
    """
    if len(sys.argv) < 3:
        print('Args: <edit-key> <filename>')
        return

    key = sys.argv[1]
    file = sys.argv[2]

    data_dict = read_file(file)
    if not data_dict:
        return

    match key:
        # example 1
        case 'ex1-dns':
            edited = ex1_dns(data_dict)
        case 'ex1-server':
            edited = ex1_server(data_dict)
        case 'ex1-internet_wanted':
            edited = ex1_internet_wanted(data_dict)

        # example 2
        case 'ex2-server':
            edited = ex2_server(data_dict)

        # example 3
        case 'ex3-server':
            edited = ex3_server(data_dict)

        # example 4
        case 'ex4-vpn-net':
            edited = ex4_vpn_net(data_dict)

        case _:
            print(f'Unknown key {key}')
            return
    
    
    write_file(edited, file)
    

if __name__ == '__main__':
    main()
