#!/usr/bin/bash
#
# Create and run all examples
#

testdir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
if [[ -z "${PYTHONPATH:-}" ]] ; then
    export PYTHONPATH=$(/usr/bin/realpath "$testdir"/../)
fi

/usr/bin/pytest -s -v test-examples.py
