py.install_sources(
  '__init__.py',
  'py.typed',
  subdir: 'wg_tool'
  )
subdir('config')
subdir('crypto')
subdir('data')
subdir('dns_resolver')
subdir('ids')
subdir('migrate')
subdir('net')
subdir('peers')
subdir('psks')
subdir('rpt')
subdir('tool')
subdir('utils')
subdir('vpn')
subdir('vpninfo')
subdir('vpns')
subdir('wg_import')

