[project]
name = "wg_tool"
description = "Wireguard VPN administration tool"
version = "10.0.0"
authors = [{ name = "Gene C", email = "arch@sapience.com" }]
license = "GPL-2.0-or-later"
readme = "README.rst"
keywords = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["meson-python", "cython >= 3.0", "meson", "ninja"]
build-backend = "mesonpy"

[tool.uv]
package = true

[tool.meson-python.args]
#install = ["--tags=runtime,python-runtime"]
install = ["--tags=python-runtime"]

[tool.mypy]
check_untyped_defs = true
follow_untyped_imports = true

[tool.pylint.main]


