[build-system]
requires = ["uv_build>=0.9.21,<=1.0.0"]
build-backend = "uv_build"

[project]
name = "wg_tool"
description = "Wireguard tool that simplifies all aspects of VPN configuration"
authors = [{ name = "Gene C", email = "arch@sapience.com" }]
license = "GPL-2.0-or-later"
readme = "README.rst"
keywords = []
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]
requires-python = ">=3.13"
version = "9.2.2"
dependencies = []

[project.urls]
Documentation = "https://github.com/gene-git/wg_tool/Docs"
Issues = "https://github.com/gene-git/wg_tool/issues"
Source = "https://github.com/gene-git/wg_tool"

[tool.uv.build-backend]
module-name = 'wg_tool'
module-root = "src"
source-include = [
    '/wg_tool',
    '/wg_tool/py.typed',
]
source-exclude = [
    ".pytest_cache",
    "__pycache__",
    ".mypy_cache",
]



[tool.mypy]
check_untyped_defs = true
# follow_untyped_imports = true

