py.install_sources(
     'acct.py',
     '__init__.py',
     'profile_base.py',
     'profile.py',
     'show_list.py',
     'tools.py',
     'wg_address.py',
     'wg_config_base.py',
     'wg_config.py',
     'wg_dns.py',
     'wg_interface.py',
     'wg_peer.py',
     'wg_write.py',
  subdir: 'wg_tool/peers'
)
