py.install_sources(
     'add_ip_group.py',
     '__init__.py',
     'modify_copy.py',
     'modify_edit.py',
     'modify_ids_to_idents.py',
     'modify_merge.py',
     'modify_nets.py',
     'modify_new.py',
     'modify_rename.py',
     'modify_save.py',
     'modify_state.py',
     'tag_to_vpn_prof.py',
     'vpns_base.py',
     'vpns.py',
  subdir: 'wg_tool/vpns'
)
