#!/usr/bin/bash
#
# Source code checks.
#
# Run in top level
# 

cd src
mod='wg_tool'
PYTHONPATH=. pylint $mod/*.py $mod/*/*.py
PYTHONPATH=. pycodestyle --max-line-length=110 $mod/*.py $mod/*/*.py

mypy --check-untyped-defs --follow-untyped-imports $mod


