#!/bin/bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: © 2022-present  Gene C <arch@sapience.com>
#
# installer script for wg_tool
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
# gene c (2022)
#
dest="$1"
self="wg_tool"

info="README.rst contrib Docs scripts packaging"
infodir="/usr/share/${self}"

license="Docs/License.rst"
licensedir="/usr/share/licenses/${self}"

etcwg='/etc/wireguard/'
scriptdir="/$etcwg/scripts"
scripts='scripts/wg-peer-updn'

# list apps without the ".py" or leave empty string
apps=('wg-tool')

# so can make app link in /usr/bin
sitedir=$(/usr/bin/python3 -c "import site; print(site.getsitepackages()[0])")

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    # shared

    /usr/bin/rsync --mkpath -a ${info} ${dest}${infodir}
    /usr/bin/rsync --mkpath -a ${license} ${dest}/${licensedir}/

    # keep /etc/wireguard same perms as wireguard-tool
    mkdir -p ${dest}/${etcwg}
    chmod 700 ${dest}/${etcwg}
    /usr/bin/rsync -a ${scripts} ${dest}/${scriptdir}/

    /usr/bin/python -m installer --destdir="$dest" dist/*.whl

    # link(s) in /usr/bin/
    if [ -v apps ] ; then
        /usr/bin/mkdir -p "${dest}/usr/bin"
        for app in ${apps[@]}
        do
            /usr/bin/ln -sf ${sitedir}/${self}/${app}.py ${dest}/usr/bin/${app}
        done
    fi
    exit 0
fi

