py.install_sources(
     'comments.py',
     'debug.py',
     'files_match.py',
     'file_tidy.py',
     'file_tools.py',
     '__init__.py',
     'msg.py',
     'qr_code.py',
     'read_write.py',
     'report.py',
     'text.py',
     'toml.py',
     'version.py',
     'yaml.py',
  subdir: 'wg_tool/utils'
)
